### ISSUE TITLE
Problems with trailing slash at the end of each request

### ISSUE THREAD

**Issue by ramsane** [robsontenorio/vue-api-query#181]
It is a standard practice that any backend would follow to add trailing slash at the end of every api request. There are few ways of handling it.

Irrespective of efforts at the backend, some browsers are appending it which creates the issue.

This can be solved by adding a trailing slash to all the requests.

Note: we can add that to the resourse, but it does creates the problem of adding additional slash when we use find() or something similar. Hope this is clear.

**Comment by ramsane** [comment]
I have django rest framework as a backend

**Comment by Peter-Krebs** [comment]
Apparently you can also solve by making the trailing `/` optional for the backend: https://stackoverflow.com/questions/46163838/how-can-i-make-a-trailing-slash-optional-on-a-django-rest-framework-simplerouter

The post is a little older but you can probably find the equivalent setting in today's version.  
This makes routing for `/user/` the same as for `/user`, which makes sense.

I think this is the better approach. It is equivalent to accesing a folder. You can access it with or without the slash.  
The only problem you were having is if `/home` was a file but `/home/` was a folder. This is possible but generally regarded as bad practice as well. It is just how file systems turned out.  
Equivalently in APIs, you expect `/user` to be the same resource as `/user/`. So it is reasonable to assume you fix the routing in the backend for all requests instead of every library individually.

**Comment by ramsane** [comment]
Thanks. We did that already. Not by the accepted answer, but by the last answer where we can use re_path to do the same.

But irrespective of the backend, sometimes browsers are appending slash at the end when we make the url request. So, that's the issue. With the current code in vue api query, we can append slash in the resource. But when we request for sub resource it appends another / makes it `/users//user_id`. 

To avoid that, we can have a parameter where we can append slash at the end or not, could solve the issue.

Besides, I don't think leaving this to the server is not a feasible solution as browsers now a days adding that trailing slash at end automatically.

Hope this is clear.

**Comment by Peter-Krebs** [comment]
Leaving this to the server (accepting both URLs with / and without) solves the issue for all browsers, for all libraries.  

There is no need to fix this in every API library if one change in the backend solves this for all of them at once.

**Comment by ramsane** [comment]
I think you are right. Even Django has some design principles and they strongly recommend to have trailing slash at the end. They won't force it. There is an option to turn it off. But few browsers are adding it and that creates an issue. 

Making changes to backend makes sense and it is the easiest solution. But having an option always helps right. This can adopt to any situations. And having slash at the end of the list URL makes it looks like requesting for a list of resources and without that is like requesting a particular resource.

**Comment by Peter-Krebs** [comment]
That is indeed a nice aspect - symbolizing the group of records with the / and an individual without.  
I think that is too subtle for most people. Vue Api Query is about elegance in usage.  
You shouldn't be bothered with that amount of implementation detail.

But let's wait what @robsontenorio and @JoaoPedroAS51 have to say.

**Comment by robsontenorio** [comment]
There is no official consent about final slash. So it depends how you build things and it does not  have to do with this package.
