### ISSUE TITLE
Using object in where

### ISSUE THREAD

**Issue by WildEgo** [robsontenorio/vue-api-query#205]
Hey guys from what it seems I can't really use

```
Model.where({
    type: this.search.type,
    team: this.search.team
});
```

I think it would be useful to avoid overwriting a lot of stuff and just basically passing a query to the current Model.

Kind Regards,
Luis Bizarro

**Comment by JoaoPedroAS51** [comment]
Hi @WildEgo! Yeah, this is not supported yet, but I really liked the idea! 😃 
It seems easy to implement. What do you think @Peter-Krebs?

**Comment by Peter-Krebs** [comment]
When queries are simple this approach is very nice to use, yes.  
It gets complicated if you want to pass the object around or modify the `where` query.

We should also add the possibility to edit the `where()` statement, with a getter and setter for the object. Otherwise it is not possible do edit the where conditions. For example, you could have a base class with default `where` options that get modified by child classes.  
It is not a use-case for me but I can imagine people want to build upon this behavior once it exists.

String parameters to `where()` with strings should be internally converted to an object in general? Isn't that what we do already?
