### ISSUE TITLE
array values are not parsing properly as per the documentation

### ISSUE THREAD

**Issue by ramsane** [robsontenorio/vue-api-query#214]
There is this line where we are parsing the custom params payload with encode: false. However, if we pass an array, it won't stringy properly. For this, we need to pass an extra parameter. 
```js
var qs = require("qs")
qs.stringify({'a':'asdf', 'b': ['a','b']}, {encode: false, arrayFormat: 'comma'})
```
will produce the output `"a=asdf&b=a,b"` as intended.

But the current code only has `encode: false` as an option. Without the arrayFormat, we will get output something like this.
```js
var qs = require("qs")
qs.stringify({'a':'asdf', 'b': ['a','b']}, {encode: false})
```
Output: `"a=asdf&b[0]=a&b[1]=b"`

link: https://github.com/robsontenorio/vue-api-query/blob/dev/src/Parser.js#L155

Hope the problem is clear.

**Comment by ramsane** [comment]
There is this line where we are parsing the custom params payload with encode: false. However, if we pass an array, it won't stringy properly. For this, we need to pass an extra parameter. 
```js
var qs = require("qs")
qs.stringify({'a':'asdf', 'b': ['a','b']}, {encode: false, arrayFormat: 'comma'})
```
will produce the output `"a=asdf&b=a,b"` as intended.

But the current code only has `encode: false` as an option. Without the arrayFormat, we will get output something like this.
```js
var qs = require("qs")
qs.stringify({'a':'asdf', 'b': ['a','b']}, {encode: false})
```
Output: `"a=asdf&b[0]=a&b[1]=b"`

link: https://github.com/robsontenorio/vue-api-query/blob/dev/src/Parser.js#L155

Hope the problem is clear.

**Comment by ramsane** [comment]
For now, I can make that string manually with `status: ['first', 'second'].join(',')` to make the string `status=first,second` manually. But I think this should be updated in the code.

**Comment by Versleijen** [comment]
Hi,

First, thank you for the great work put in vue-api-query!
We are using vue-api-query for some time now and we are running into problems caused by this change.
Our backend (Laravel, PHP) can handle the old way (`"a=asdf&b[0]=a&b[1]=b"`) of parsing the array values out of the box. For the new way (`"a=asdf&b=a,b"`) we need to make changes the get an array.

In my opinion the old way (`"a=asdf&b[0]=a&b[1]=b"`) is more supported in backend frameworks. At least we should have the option to choose which formatting we would want to use. Or is there an easier way to make this works for Laravel?
See also this discussion on StackOverflow: https://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string
