### ISSUE TITLE
Extra arguments (params) to find method

### ISSUE THREAD

**Issue by avido** [robsontenorio/vue-api-query#230]
Is it possible to append params when using the `find` method ?

eg.
```javascript
const Product = product.params({filter: 'some'}).find(1);
```

**Comment by Peter-Krebs** [comment]
The `find()` function gets you a record with a specific ID. So no need for query parameters, since you are not searching.

You can achieve the same with `where`, `whereIn`, `params` in combination with `first()` at the end.  
See [Query Builder Documentation](https://robsontenorio.github.io/vue-api-query/api/query-builder-methods)
