### ISSUE TITLE
Default resource name does not work when building nuxt.

### ISSUE THREAD

**Issue by fillefilip8** [robsontenorio/vue-api-query#6]
https://github.com/robsontenorio/vue-api-query/blob/e0dfdf6f6d19ad3fc3ae10ee17c9474860a48636/src/Model.js#L40

Overriding resource() works but not the default return.

**Comment by robsontenorio** [comment]
Can you share your full domain class implementation?

**Comment by fillefilip8** [comment]
Basically just the example.
![img](https://i.mlgimg.xyz/d216c479.png)
If i don't override the resource(): 
![img](https://i.mlgimg.xyz/7875b64f.png)

Code: 
```javascript 
let users = await User.get()
```

If I override the resource(): 
![img](https://i.mlgimg.xyz/c3e34586.png)
It will just work as expected.

**Comment by robsontenorio** [comment]
Right now is working as expected. What is your NUXT and VUE-API-QUERY version?

Can you show the full implementation of `User` class, including the imports? And your base model as well? Maybe some typo. 

—
Robson Tenório

Em 18 de abr de 2018, à(s) 17:24, fillefilip8 <notifications@github.com> escreveu:

**Comment by zhi8617** [comment]
I met the same problem.
If I run npm run watch , It works fine. 
But if run production, An error will occur. ( The letters will be missing )
So I try the custom method.

**Comment by robsontenorio** [comment]
@fillefilip8  I can confirm.  But, unfortunaly, it can not be fixed right now due to webpack/uglify restrictions. So `this.constructor.name` is not available when building.

For now, it is necessary always implement the `resource()` method for all domain models. Just updated the README. 

@zhi8617 

It is not necessary to use `custom()` method. Just implement the `resource()` method as described on README
